services:
  backend:
    build:
      context: ./API
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    env_file:
      - ./API/.env
    depends_on:
      - postgres

  frontend:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: DBNAME
      POSTGRES_USER: DBUSER
      POSTGRES_PASSWORD: DBPASS
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: